MXMLC = /home/donghee/work/flexsdk3.4/bin/mxmlc
FLIXEL = ../flixel_v1.0
SRC = HelloWorld.as PlayState.as
MAIN = HelloWorld.as
SWF = Game.swf

$(SWF) : $(SRC)
	$(MXMLC) -sp $(FLIXEL) -o $(SWF) -- $(MAIN)
